# Generated by Django 5.2.10 on 2026-01-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarePlanJob',
        ),
    ]
